version: "3.9"

services:
#  app:
#    image: "test"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    env_file:
#      - .env_dev.env
#    volumes:
#      - ${PWD}/database:/app/wiki/database
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      PGDATA: /pgdata
    volumes:
      - "postgres_data:/pgdata"
    user: "2000"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: